apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    application: mlbparks
    createdBy: template-mlbparks-eap
  name: {{ .Values.application_name }}
spec:
  dockerImageRepository: ""
  tags:
  - name: latest
