apiVersion: v1
kind: Service
metadata:
  labels:
    application: mlbparks
    createdBy: template-mlbparks-eap
  name: mongodb
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    deploymentConfig: {{ .Values.application_name }}-mongodb
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The web server's http port
  labels:
    application: mlbparks
    createdBy: template-mlbparks-eap
  name: {{ .Values.application_name }}
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deploymentConfig: {{ .Values.application_name }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Ping service for clustered applications
  labels:
    application: mlbparks
    createdBy: template-mlbparks-eap
  name: {{ .Values.application_name }}-ping
spec:
  ports:
  - port: 8888
    targetPort: 8888
  selector:
    deploymentConfig: {{ .Values.application_name }}
